version: "3"
services:
  mock-api:
    build:
      dockerfile: ./Dockerfile
      target: json-server
    ports:
      - 3000:3000

  webapp:
    # depends_on:
    #   - mock-api
    build:
      dockerfile: ./Dockerfile
      target: http-server
    ports:
      - 4200:4200
    environment:
      - PORT=4200
